Package skeleton
IBM/carbon-shared-tests pull request #1
Opened 2020-05-11 15:41 UTC by elizabethsjudd

## Changelog

### Summary

Basic package file setup that is expected to change/grow as the package is filled out. This PR does not contain any source code related to the actual package deliverables.

### Added

- package.json
- .editorconfig
- GitHub issue and PR templates
- .gitignore
- .nvmrc
- CONTRIBUTING.md

### Updated

- README.md

## Code review

- [x] The code must be reviewed by at least one Maintainer

## Code quality

Manual testing to be completed by reviewers

- [ ] Documentation is understandable

## Compliance requirements

- [x] The pull request must have a link to GitHub issue

Related to https://github.ibm.com/Watson-Health/design-library/issues/5912

## Definition of done

- The code has been reviewed by the Maintainer
- The code has passed quality checks
- Documents are updated

2020-05-11 15:56 UTC, Donisius approved these changes
Awesome!

2020-05-11 16:59 UTC, scottnath requested changes

2020-05-11 16:59 UTC, scottnath commented on .nvmrc
> +v10
```suggestion
v12
```

Carbon is currently on Node 12:
https://github.com/carbon-design-system/carbon/blob/master/package.json#L8
https://github.com/carbon-design-system/carbon/blob/master/.nvmrc

Although [carbon-angular is on Node 10](https://github.com/IBM/carbon-components-angular/blob/master/.nvmrc), it does seem more future-proof if we attempt to start out this repo on Node 12

I would suggest this repo uses Node 12. We can set up testing to ensure it continues to work on Node 10. Node 10 kicks to maintenance mode in 8 days and Node 14 is considered the current release.

![lts schedule](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)

2020-05-11 16:59 UTC, scottnath commented on CONTRIBUTING.md
> +* Follow the project coding conventions
Is this referring to a specific set of conventions that should be referenced here?

2020-05-11 16:59 UTC, scottnath commented on CONTRIBUTING.md
> +Note: if your pull request isn't getting enough attention, you can contact the maintainer to find a reviewer
should we have a `CODEOWNERS` to link to here?

2020-05-11 16:59 UTC, scottnath commented on package.json
> +    "node": "^10"
```suggestion
    "node": "^12"
```

2020-05-11 17:36 UTC, elizabethsjudd commented on CONTRIBUTING.md
> +* Follow the project coding conventions
At this point it does not.  Most of this documentation was copied and pasted from the WH InnerSource templates we used for Exported Tests.

2020-05-11 17:37 UTC, elizabethsjudd commented on CONTRIBUTING.md
> +Note: if your pull request isn't getting enough attention, you can contact the maintainer to find a reviewer
We don't have CODEOWNERS at this point since there aren't any source files to align them too.  That's also something we'd want to discussion with Carbon as to who those code owners should be.

2020-05-11 17:44 UTC, cal-smith approved these changes
🎉 Looks good to me!

2020-05-11 18:01 UTC, elizabethsjudd commented
@scottnath ready for re-review. See the comments answering your questions.

2020-05-11 20:06 UTC, scottnath approved these changes

2020-05-13 13:42 UTC, ChevonNwosu approved these changes

2020-05-13 16:01 UTC, merged